name: Close Snaps

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  close:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Close obsolete channels
      uses: canonical/actions/close-snap@cb345b48c77065507280f3dd9d4f42299af2d1a6 # release @ 2026.06.25
      continue-on-error: true
      with:
        channel: edge/pr${{ github.event.number }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
